version: '3'

services:

  # Nginx 서비스 (로드 밸런서 역할)
  nginx:
    image: nginx:latest  # Nginx 이미지
    container_name: nginx
    ports:
      - "50050:50050"  # Nginx가 50050 포트에서 HTTP 요청을 받음
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # 위에서 작성한 Nginx 설정 파일을 마운트
      - ./logs:/var/log/nginx  # Nginx 로그를 호스트 시스템과 마운트
